analise_estrutura:
  description: >
    Com base na seguinte mensagem de commit: "{input}",
    realize uma inspeção na estrutura do projeto, mapeando diretórios, arquivos e padrões utilizados.
    Considere como essa mudança pode impactar a organização do código.
  expected_output: >
    Relatório arquitetura_atual.md com estrutura, sugestões e justificativas técnicas relacionadas à mudança.
  agent: senior_architect

analise_heuristicas:
  description: >
    Considerando o commit informado: "{input}",
    analise as integrações, bibliotecas externas e APIs afetadas pela mudança.
  expected_output: >
    Documento analise_heuristicas_integracoes.md com mapa de integrações e sugestões com base na alteração feita.
  agent: senior_analytics

analise_solid:
  description: >
    Com base no commit: "{input}",
    avalie a aderência da mudança aos princípios S.O.L.I.D., identificando possíveis violações ou melhorias.
  expected_output: >
    Relatório analise_solid.md com violações e recomendações de refatoração baseadas na alteração feita.
  agent: quality_consultant

padroes_projeto:
  description: >
    A partir da seguinte descrição de commit: "{input}",
    avalie se há aplicação correta ou ausência de padrões de projeto como Singleton, Strategy ou Factory.
  expected_output: >
    Documento padroes_de_projeto.md com sugestões aplicadas ao cenário descrito no commit.
  agent: quality_control_manager

summarize_analysis:
  description: >
    Com base na análise técnica a seguir: "{analysis_result}",
    escreva um resumo objetivo e claro descrevendo o que foi implementado no código analisado com base nas boas práticas de Pull Request.
  expected_output: >
    Um parágrafo bem estruturado com as alterações realizadas, pronto para ser usado como descrição de um Pull Request em (pt-br).

mentoring_task:
  description: > 
    Com base nas análises técnicas realizadas,
    identifique oportunidades de aprendizado e sugira recursos educacionais personalizados para ajudar o desenvolvedor a melhorar suas habilidades técnicas.
  expected_output: >
    Documento sugestoes_aprendizado.md com recursos educacionais específicos (artigos, cursos, vídeos) organizados por tópico e conectados aos problemas identificados.
  agent: code_mentor

policy_analytics:
  description: >
    Crie um relatório sobre a política de coleta de dados do "{IA_PROVIDER}" para o modelo "{IA_MODEL}"
    com base na documentação oficial.
  expected_output: >
    Relatório data_collect_policy.md com um resumo dos principais pontos sobre a política de coleta de dados do provedor.
  agent: dataCollect_policy_analytics

lgpd_judging:
  description: >
    Com base nas leis LGPD e no relatório da analise da documentação,
    determine se o provedor da api key está respeitando ou não as leis LGPD e justifique o julgamento apontando as provas, por meio de um relatório, onde a primeira linha **exatamente na linha 1** do arquivo é a resposta antecipada (sim ou não).
  expected_output: >
    Documento status_lgpd.md com as provas ou artigos utilizados para determinar a decisão tomada.
  agent: lgpd_judge